# Server config
server:
  port: ${PORT:8080}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8083}/eureka/
    registerWithEureka: false

# Ribbon config
ribbon:
   eureka:
    enabled: true

# Zuul config
zuul:
  prefix: /api
  routes:
    autoattendents:
      path: /autoattendents/**
      serviceId: autoattendent-service
    huntgroups:
      path: /huntgroups/**
      serviceId: huntgroup-service

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false